#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind": "CustomResourceDefinition"}), expects="0+"
---
metadata:
  #@overlay/remove
  creationTimestamp: null
  #@overlay/remove
  annotations:
spec:
  validation:
    openAPIV3Schema:
      properties:
        #@overlay/remove
        metadata:
#@overlay/remove
status:
